build: off

platform:
    - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
    
branches:
  only:
    - master

init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: "6.9.2"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run dist

test_script:
  - npm run test

artifacts:
  - path: dist\DataLoggerGrapher*.exe
    name: DataLoggerGrapher.exe,
    
  - path: dist\latest.yml
    name: latest.yml

deploy:
  release: $(appveyor_repo_tag_name)
  description: $(appveyor_repo_commit_message)
  provider: GitHub
  auth_token:
    secure: Z2FZ/HNODYB1tszgZxuYPEK6pKBLE44ZI/8Afx2ky1GyFVIGWOmjHMo8j4gFROvo # your encrypted token from GitHub
  artifact: DataLoggerGrapher.exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only